[project]
name = "audio-llm-yandex-camp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.9.0",
    "dotenv>=0.9.9",
    "grpcio-tools>=1.73.1",
    "protobuf>=6.31.1",
    "sentencepiece>=0.2.0",
    "speechkit>=2.1.0",
    "torch>=2.7.1",
    "transformers>=4.53.3",
]
